{{- if .Values.nodeLifecycleController.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "local-ccm.fullname" . }}-nlc
  labels:
    {{- include "local-ccm.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-lifecycle-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "local-ccm.fullname" . }}-nlc
subjects:
- kind: ServiceAccount
  name: {{ include "local-ccm.fullname" . }}-nlc
  namespace: {{ .Release.Namespace }}
{{- end }}
