{{- if .Values.nodeLifecycleController.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-lifecycle-controller.fullname" . }}
  labels:
    {{- include "node-lifecycle-controller.labels" . | nindent 4 }}
{{- end }}
