{{- if .Values.nodeLifecycleController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-lifecycle-controller.fullname" . }}
  labels:
    {{- include "node-lifecycle-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nodeLifecycleController.replicaCount }}
  selector:
    matchLabels:
      {{- include "node-lifecycle-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "node-lifecycle-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "node-lifecycle-controller.fullname" . }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsNonRoot: false
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
      - name: controller
        image: "{{ .Values.nodeLifecycleController.image.repository }}:{{ .Values.nodeLifecycleController.image.tag }}"
        imagePullPolicy: {{ .Values.nodeLifecycleController.image.pullPolicy }}
        command:
        - /node-lifecycle-controller
        args:
        {{- if .Values.nodeLifecycleController.nodeSelector }}
        - --node-selector={{ .Values.nodeLifecycleController.nodeSelector }}
        {{- end }}
        {{- if .Values.nodeLifecycleController.protectedLabels }}
        - --protected-labels={{ .Values.nodeLifecycleController.protectedLabels }}
        {{- end }}
        - --not-ready-timeout={{ .Values.nodeLifecycleController.notReadyTimeout }}
        - --ping-timeout={{ .Values.nodeLifecycleController.pingTimeout }}
        - --ping-count={{ .Values.nodeLifecycleController.pingCount }}
        - --reconcile-interval={{ .Values.nodeLifecycleController.reconcileInterval }}
        - --leader-elect={{ .Values.nodeLifecycleController.leaderElection.enabled }}
        - --leader-elect-id={{ .Values.nodeLifecycleController.leaderElection.resourceName }}
        - --namespace=$(POD_NAMESPACE)
        - --dry-run={{ .Values.nodeLifecycleController.dryRun }}
        - --v={{ .Values.nodeLifecycleController.verbosity }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          capabilities:
            add:
              - NET_RAW
          runAsUser: 0
        resources:
          {{- toYaml .Values.nodeLifecycleController.resources | nindent 10 }}
{{- end }}
