##
## @section Common parameters
##

## @typedef {struct} Subnet - Subnet of a VPC
## @field {string} name - Subnet name
## @field {string} [cidr] - IP address range

## @param {[]Subnet} subnets - Subnets of a VPC
subnets: []
## Example:
## subnets:
##   - name: mysubnet0
##     cidr: "172.16.0.0/24"
##   - name: mysubnet1
##     cidr: "172.16.1.0/24"
