lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.37.7@sha256:981f76e37dd3552e895b4c477f024e8e567017b6d0eb09dadcb2958be7e42554
  debug: false
  localK8sAPIEndpoint:
    enabled: true
