lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.40.4@sha256:475125ca4b7fc2ab936ef81211976dc44328f9e3c4dfad3c678fa8d516714d10
  debug: false
  localK8sAPIEndpoint:
    enabled: true
