lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.39.4@sha256:88abeaae6b1147ed12a45bad5f2c8e2d724d95195f46eb049d011631fb9be70e
  debug: false
  localK8sAPIEndpoint:
    enabled: true
