lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.41.0@sha256:c89f47352f0606dd475fe90e19fe2c6e13580af5c9af3f01f356efb4f5c7375e
  debug: false
  localK8sAPIEndpoint:
    enabled: true
