lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.39.2@sha256:eb1186a56be49a9e6d65dad7b95febc6446b555d1d2dadf337e9c4a75c43193b
  debug: false
  localK8sAPIEndpoint:
    enabled: true
