lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.41.4@sha256:26bc948cce31408259034f8626cbddd594774102d21cbae86e4a9c9b41d32b17
  debug: false
  localK8sAPIEndpoint:
    enabled: true
