lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.38.7@sha256:48aee94ab6753b288134977819c67df23d3b12fd7d443123cb3e42c9b9ab6ee9
  debug: false
  localK8sAPIEndpoint:
    enabled: true
