lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.39.0@sha256:cb264b193256dd5db79ba50ad44fc2301fb19ac34155f6f6638d6cadfd45e370
  debug: false
  localK8sAPIEndpoint:
    enabled: true
