lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.41.8@sha256:0bfce72a67a36b79cf718fada94809b16b4012b6703b1e053f7fe9b12a7b54f0
  debug: false
  localK8sAPIEndpoint:
    enabled: true
