lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.39.3@sha256:044ab44440280de6d9f87791719add0cfeaa630ff655eff7ccbaf35694bbdb6b
  debug: false
  localK8sAPIEndpoint:
    enabled: true
