lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.40.5@sha256:52ed08d508df884686680557707186965e17a48e268bb7f2bdc303f18b6c518a
  debug: false
  localK8sAPIEndpoint:
    enabled: true
