lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v1.0.0-beta.1@sha256:c69bb2c14bcaca0c60fcd3f42e0876cd77854191663a0b01275d2d5576250053
  debug: false
  localK8sAPIEndpoint:
    enabled: true
