lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.39.4@sha256:7262f91a66ce9b133cff7d6d6c6f6330dbc12536f0c627f9ab6febbec26a76d4
  debug: false
  localK8sAPIEndpoint:
    enabled: true
