lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.40.0@sha256:792ca90d9e8d2d03cb10587d5a3570dad6c199e5ad0734d334869b9d595e748f
  debug: false
  localK8sAPIEndpoint:
    enabled: true
