lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.38.3@sha256:20261c17e77d34daa08569e1f34613bc27ed5b147415a6a7292505970a5b30b3
  debug: false
  localK8sAPIEndpoint:
    enabled: true
