lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.38.4@sha256:557e6cee3dfce7ec9e69b404806c6b3c3766fa523cb3dc1cbd7155c24af2cc96
  debug: false
  localK8sAPIEndpoint:
    enabled: true
