lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.38.5@sha256:708725bba1493984a0cce1d7abe16f4fb398db0f15fa4ed64930457572ef7dec
  debug: false
  localK8sAPIEndpoint:
    enabled: true
