lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v1.0.0-alpha.1@sha256:887c264efecb31cb7ca38034ecf325cf461e2302d703422364d8b20e4f18c56b
  debug: false
  localK8sAPIEndpoint:
    enabled: true
