lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.37.9@sha256:5c6e7b2b7e062b88bbf946e1fb3beb1e162526077ba8635515b5b4291d1a78e2
  debug: false
  localK8sAPIEndpoint:
    enabled: true
