lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:latest@sha256:452f8ab78ba28f5d3cf1631296bb911320a48e7e662046cb921b5ec9c95ef889
  debug: false
  localK8sAPIEndpoint:
    enabled: true
