lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.40.0@sha256:d258f97a59ceb29d0b92acec79c163725b1390249960d502cbad24efb8ee6a68
  debug: false
  localK8sAPIEndpoint:
    enabled: true
