lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.37.10@sha256:bcb95c433ce24793ce1350c4f094d9d53a7c56f5415506c88f261949da42711a
  debug: false
  localK8sAPIEndpoint:
    enabled: true
