lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.41.5@sha256:79a820c05257794569a1772b793325189db30992404957ed066d9871e0f25309
  debug: false
  localK8sAPIEndpoint:
    enabled: true
