lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.37.6@sha256:3257848553c707171dfc10ebf9c543ef8ef730ed67f595389f8c686ca3c1c84a
  debug: false
  localK8sAPIEndpoint:
    enabled: true
