lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.41.1@sha256:641d9a72b64ab68dd6f5b91de213e38f5587302cde3860c9395d3eff420f3924
  debug: false
  localK8sAPIEndpoint:
    enabled: true
