lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.41.2@sha256:02134eda80df3ebd348d603ace428ae2109f713a42023fe9891cd338d542ecc1
  debug: false
  localK8sAPIEndpoint:
    enabled: true
