lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.38.6@sha256:e33a03683a852a1ac53065898e36a5c4f93dff18b5ead66449be2655619e9629
  debug: false
  localK8sAPIEndpoint:
    enabled: true
