lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:latest@sha256:4b4afb13fa6e04871dc3d31ce406e5f06c2bb46f157da367f47a7da80ec1a0be
  debug: false
  localK8sAPIEndpoint:
    enabled: true
