lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:latest@sha256:4e60a1b13a2a28792ef1a5c4d7875dca2c869e09d7360f0766a7485937fe7977
  debug: false
  localK8sAPIEndpoint:
    enabled: true
