lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.40.6@sha256:bd1479489dab680c615fab1cd5deaaff3c602df94bc0f622a4f8b6dfb44c2d5d
  debug: false
  localK8sAPIEndpoint:
    enabled: true
