{{- $cozystack := .Values.cozystack | default dict }}
{{- $publishing := $cozystack.publishing | default dict }}
{{- $certificates := $publishing.certificates | default dict }}
{{- $host := $publishing.host | default "" }}
{{- $issuerType := $certificates.issuerType | default "http01" }}
{{- $exposeIngress := $publishing.ingressClassName | default "tenant-root" }}
{{- if not $host }}
{{- fail "ERROR: cozystack.publishing.host is required" }}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- if ne $issuerType "cloudflare" }}
    acme.cert-manager.io/http01-ingress-class: {{ $exposeIngress }}
    {{- end }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $exposeIngress }}
  tls:
  - hosts:
      - keycloak.{{ $host }}
    secretName: web-tls
  rules:
  - host: keycloak.{{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-http
            port:
              name: http
