apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cloud-config
data:
  cloud-config: |
    loadBalancer:
      creationPollInterval: 5
      creationPollTimeout: 60
      enableEPSController: true
      selectorless: true
    namespace: {{ .Release.Namespace }}
    infraLabels:
      apps.cozystack.io/application.group: apps.cozystack.io
      apps.cozystack.io/application.kind: Kubernetes
      apps.cozystack.io/application.name: {{ .Release.Name | trimPrefix "kubernetes-" }}
      internal.cozystack.io/tenantresource: "true"
