{{- $cozystack := .Values._cozystack | default dict }}
{{- $issuerType := dig "publishing" "certificates" "issuerType" "http01" $cozystack }}
{{- $namespace := .Values._namespace | default dict }}
{{- $ingress := dig "ingress" "" $namespace }}
{{- $host := dig "host" "" $namespace }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bootbox
  labels:
    app: bootbox
  annotations:
    {{- if ne $issuerType "cloudflare" }}
    acme.cert-manager.io/http01-ingress-class: {{ $ingress }}
    {{- end }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- if .Values.whitelistHTTP }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ join "," (.Values.whitelist | default "0.0.0.0/32") }}"
    {{- end }}
spec:
  ingressClassName: {{ $ingress }}
  tls:
    - hosts:
        - "{{ printf "bootbox.%s" (.Values.host | default $host) }}"
      secretName: bootbox-tls
  rules:
    - host: "{{ printf "bootbox.%s" (.Values.host | default $host) }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: bootbox
                port:
                  name: http
