cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.38.5@sha256:df4769c334eebc0f9bb09f412d14866df616e1e1da03cb2b3ab9b440fda6c707
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
