cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.41.3@sha256:437050c896017bc9f402013c67d0889c83ca570f447fcde9d59f57b9c781673e
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
