cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.37.10@sha256:04772e898edbab0613ff2beb0b7d62196b47d986488ef0c67b86946b69b30f24
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
