cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.37.8@sha256:ea13563f31ea1ccd59825537e18eb506137e1c74521b2c7c82626d29f6a1e22c
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
