cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.40.5@sha256:251a100c13858f44b61f70c009fcee02ad8181ddce20b3f601dcc41bb0e6f0d0
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
