cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.41.6@sha256:f6062e742bfe8f77b35c5a7373d66f3561f1dbca93c31d1e8162f05cd8893859
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
