cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.39.0@sha256:d9669a49fd22b3f1ed56aa21857f99c63e88426488530092f606ad275f6ce650
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
