cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.37.6@sha256:d4f461af111e1b68d67d80fc598b75171b72239ac195dc8ea522bddd0ed76561
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
