cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.37.7@sha256:d7945e20fe26ecdaa1ebd9729a095cac64391ac2a0224b459f07c5819d56ff37
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
