cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.40.0@sha256:8b8d00c8d7d8c5b5e36216c7454bd107e355ad2a76e2a96883a6e234fbeb8856
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
