cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.38.4@sha256:58dba7b8b9915ece3a5785b6178536377fce56dc55451f2736415cdeab9185ff
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
