cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.39.1@sha256:fa6bd65b041e75bb2f11f0e564dc78060ab12091188e0d7e03161fec68e03014
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
