cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v1.0.0-beta.1@sha256:d14ff50313b855fc90f3261ef223f52db5831ab49aa3ce3812848d2347fb7f03
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
