cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.41.5@sha256:76785df802f80a3f8b2591371694cab2463ef442504a6a22b5f6543754f48cbb
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
