cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.39.2@sha256:e859dc81b4905fa163b75b1d567e91bd1eac572f85931954c2dc646cb07d3959
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
