cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.40.3@sha256:1b5109bc4149178084941cf1cb505110c581c9326dbb1ef94ffdcdb026dff0e8
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
