cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.41.9@sha256:b0dad94a222192422eeb4b60d4b8835fe3e19d0e1c782745a61838301a58e92e
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
