cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.41.2@sha256:6e6ba67d28d852aeb867c9d2b8197e3e189a8088210a833a1bb7670072c36f79
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
