cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.38.3@sha256:123d8afa32bf2935fcffafdfa52366f799bbef2f8ecae5251925c212bdbe3236
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
