cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.40.6@sha256:9a6120fd2884efc390c489cf1cf18b367f3ab09f28b186b4a479704a0a23b68f
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
