cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.38.6@sha256:ed2e29c1ca8c4030d63368fa2dc2b02588679a3df416aca73d8e30efc87542bd
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
