cilium:
  kubeProxyReplacement: true
  hostFirewall:
    enabled: true
  hubble:
    enabled: false
  externalIPs:
    enabled: true
  nodePort:
    enabled: true
  loadBalancer:
    algorithm: maglev
    serviceTopology: true
  ipam:
    mode: "kubernetes"
  image:
    repository: ghcr.io/cozystack/cozystack/cilium
    tag: latest
    digest: "sha256:3f10e934afbb73df214f7789a4b98b5cd6b66ca300a2abfc6553e10905d74fc5"
  envoy:
    enabled: false
  rollOutCiliumPods: true
  operator:
    rollOutPods: true
    replicas: 1
