cilium:
  kubeProxyReplacement: true
  hostFirewall:
    enabled: true
  hubble:
    enabled: false
  externalIPs:
    enabled: true
  nodePort:
    enabled: true
  loadBalancer:
    algorithm: maglev
    serviceTopology: true
  ipam:
    mode: "kubernetes"
  image:
    repository: ghcr.io/cozystack/cozystack/cilium
    tag: 1.18.5
    digest: "sha256:c14a0bcb1a1531c72725b3a4c40aefa2bcd5c129810bf58ea8e37d3fcff2a326"
  envoy:
    enabled: false
  rollOutCiliumPods: true
  operator:
    rollOutPods: true