cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.40.1@sha256:75636007f63e1b2cb51fc2e70782b707330d1e728c32642a4edc500b614f0781
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.40.1"
  cozystackAPIKind: "DaemonSet"
