cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.39.4@sha256:94fde65fe25af01c977db2b16a64703b740f2833f9c878894a8cc8247de21fa2
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.39.4"
  cozystackAPIKind: "DaemonSet"
