cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.41.3@sha256:b7e26e6500c5cccbacd7cde51d8f4872136d04483ee0d48d35cc3b1174cda997
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.41.3"
  cozystackAPIKind: "DaemonSet"
