cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v1.0.0-beta.1@sha256:c1113be0cf66d6bd24f24cee4ebdaf3f680478cefb84c93f902e47ed27bb6bc8
  debug: false
  disableTelemetry: false
  cozystackAPIKind: "DaemonSet"
