cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.37.5@sha256:0d339b30ce2d07634dd19176e6966c5bd722872b12e47176b4243abb5704a11f
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.37.5"
