cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.38.3@sha256:ea9627e173e2d981cdf2d2106cb5bb153c0ae2be63ff8825cbe6f9b6e966825c
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.38.3"
  cozystackAPIKind: "DaemonSet"
