cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.41.2@sha256:eddf1a193d58903f4be6cdb4d1f936228a76e50831e644836b0fae5ff9b32e4c
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.41.2"
  cozystackAPIKind: "DaemonSet"
