cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.40.0@sha256:392f62ac283212c391e524eaad8845bc34a5916ff32dfdf37ad2962b9eff1da8
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.40.0"
  cozystackAPIKind: "DaemonSet"
