cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.39.2@sha256:b96283a1774f23735849802069a907cb85f4fd57df89f8740a954a7d2922afc3
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.39.2"
  cozystackAPIKind: "DaemonSet"
