cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.37.10@sha256:224871a6e8f7a80d2b6476b57b6176c472afe112b503a5c5bf151b945d78a407
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.37.10"
  cozystackAPIKind: "DaemonSet"
