cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.38.5@sha256:b61877718f2e86e4d26c1452120e5c4f5bf665f8d639e411117aa148814d526d
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.38.5"
  cozystackAPIKind: "DaemonSet"
