cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.40.6@sha256:7c935cb96af9486e5afbb0d8bfa132cadc44bc8818aa51ef69b465c5d6ad6ab7
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.40.6"
  cozystackAPIKind: "DaemonSet"
