cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.38.8@sha256:6be8fa0a56c0dca71086deddef1b16d23c613b912c7ca379096ca3ad0e50dffb
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.38.8"
  cozystackAPIKind: "DaemonSet"
