cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:latest@sha256:44679c58a9a8d5431dba9b4b512ec97cb252750fd30914c5afa4addf00f50479
  debug: false
  cozystackAPIKind: "DaemonSet"
