cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.39.0@sha256:af229b1d63705af9eb8bbf6867b4e94412516cd41ecfbc73f7fb19ac705e739a
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.39.0"
  cozystackAPIKind: "DaemonSet"
