cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.36.3@sha256:341b3d89455318ea8c230d9098397af807ac765a602fe949ac86053dd377b856
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.36.3"
