cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.41.1@sha256:b9d067bea8bac4e99648ddc377a0a84f3215335f2693b2c948fa80a83539bec9
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.41.1"
  cozystackAPIKind: "DaemonSet"
