cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.41.4@sha256:ffebcdf0cea7e3acc0e80b8e381dfd2199fb3bc80537f772b9a93f65457bc2d8
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.41.4"
  cozystackAPIKind: "DaemonSet"
