cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.37.4@sha256:fdd9481ccb60789930412febde2c9970d720b02522f0709ab0211e7cbdaed447
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.37.4"
