cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.38.6@sha256:f16a5372e4d30f7eb68fec8efb7d4a5901d107841e6c826c0dedfb16471550b9
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.38.6"
  cozystackAPIKind: "DaemonSet"
