cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.41.8@sha256:6850a8aace4fa998faa33fc06e2ff8d6034141c31541fd0f6368156d19943838
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.41.8"
  cozystackAPIKind: "DaemonSet"
