cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.41.0@sha256:5cea23058c5d0f5370c57c901cefd9638ce31bfb995a3d7d07ca137b3768dffb
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.41.0"
  cozystackAPIKind: "DaemonSet"
