cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.40.3@sha256:2b4ad67116c03cd001c495001f9032e6d944199f14a2d80a24d697e2293650c3
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.40.3"
  cozystackAPIKind: "DaemonSet"
