cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.37.7@sha256:fbfaba268cddd6e66949cd56154ff408f3da83f05567f1645e0299369d51f67d
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.37.7"
  cozystackAPIKind: "DaemonSet"
