cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.37.9@sha256:68cc087920f41768447bffac4d77e7b38025eee96a499fa092d1d9461bcac23a
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.37.9"
  cozystackAPIKind: "DaemonSet"
