cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.40.4@sha256:2af95424614d47cc7e25b895b030eea2f65aa41f331eb15f7cef5335d4b0821d
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.40.4"
  cozystackAPIKind: "DaemonSet"
