cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.40.5@sha256:95068e53e3bf942a6b8da910f2a5be77c2e9efa2a4067c16e80a92334eb5ddf4
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.40.5"
  cozystackAPIKind: "DaemonSet"
