cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.41.7@sha256:007deee61a161bc0eb5fad68cbe6ae5a7b080d083122a3884610aa64011f8235
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.41.7"
  cozystackAPIKind: "DaemonSet"
