cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.39.5@sha256:dd6bb910842151ec60cea74f43b03ac35f461a03f6fe4370b12c7aaf48fee7b8
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.39.5"
  cozystackAPIKind: "DaemonSet"
