---
apiVersion: v1
kind: Secret
metadata:
  name: cozystack-values
  namespace: tenant-root
  labels:
    reconcile.fluxcd.io/watch: Enabled
    internal.cozystack.io/managed-by-cozystack: ""
type: Opaque
stringData:
  values.yaml: |
    _cluster:
      {{- .Values._cluster | toYaml | nindent 6 }}
    _namespace:
      host: {{ index .Values._cluster "root-host" | quote }}
      etcd: tenant-root
      ingress: tenant-root
      monitoring: tenant-root
      seaweedfs: tenant-root
