apiVersion: v1
kind: Service
metadata:
  name: flux-plunger
  labels:
    app.kubernetes.io/name: flux-plunger
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: flux-plunger
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  - name: health
    port: 8081
    targetPort: 8081
