{{- if .Values.nfs.instances }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-nfs-driver
  labels:
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: {{ .Release.Name }}
    sharding.fluxcd.io/key: tenants
spec:
  releaseName: nfs-driver
  chartRef:
    kind: ExternalArtifact
    name: cozystack-kubernetes-application-kubevirt-kubernetes-nfs-driver
    namespace: cozy-system
  kubeConfig:
    secretRef:
      name: {{ .Release.Name }}-admin-kubeconfig
      key: super-admin.svc
  targetNamespace: cozy-nfs-driver
  storageNamespace: cozy-nfs-driver
  interval: 5m
  timeout: 10m
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    force: true
    remediation:
      retries: -1
  valuesFrom:
  {{- range .Values.nfs.instances }}
  {{- $secretName := printf "nfs-%s-credentials" .name }}
  - kind: Secret
    name: {{ $secretName }}
    valuesKey: host
    targetPath: extraStorageClasses.nfs-{{ .name }}.server
  - kind: Secret
    name: {{ $secretName }}
    valuesKey: port
    targetPath: extraStorageClasses.nfs-{{ .name }}.port
  - kind: Secret
    name: {{ $secretName }}
    valuesKey: path
    targetPath: extraStorageClasses.nfs-{{ .name }}.share
  {{- end }}
  values:
    csi-driver-nfs:
      storageClass:
        create: false
    {{- with .Values.addons.nfs.valuesOverride }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  dependsOn:
  {{- if lookup "helm.toolkit.fluxcd.io/v2" "HelmRelease" .Release.Namespace .Release.Name }}
  - name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
  - name: {{ .Release.Name }}-cilium
    namespace: {{ .Release.Namespace }}
{{- end }}
