---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.mariadb-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: default
      dependsOn:
        - cozystack.networking
        - cozystack.mariadb-operator
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      components:
        - name: mariadb
          path: apps/mariadb
          libraries: ["cozy-lib"]
        - name: mariadb-rd
          path: system/mariadb-rd
          install:
            namespace: cozy-system
            releaseName: mariadb-rd
