---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: flux
    app.kubernetes.io/part-of: flux
  name: flux
  namespace: cozy-fluxcd
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http-sc
  selector:
    app.kubernetes.io/name: flux
  type: ClusterIP
