---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.bootbox-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: default
      dependsOn:
        - cozystack.networking
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      components:
        - name: bootbox-application
          path: system/bootbox-application
          install:
            releaseName: bootbox-application
            namespace: cozy-system
        - name: bootbox
          path: apps/bootbox
          libraries: ["cozy-lib"]
        - name: bootbox-rd
          path: system/bootbox-rd
          install:
            namespace: cozy-system
            releaseName: bootbox-rd
