---
apiVersion: cozystack.io/v1alpha1
kind: PackageSetDefinition
metadata:
  name: cozystack.bootbox-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: default
      dependsOn:
        - cozystack.networking
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      packages:
        - name: bootbox-application
          path: system/bootbox-application
          releaseName: bootbox-application
          namespace: cozy-system
      sources:
        - name: bootbox
          path: extra/bootbox
          libraries:
            - cozy-lib

