velero:
  image:
    repository: ghcr.io/cozystack/cozystack/velero
    tag: latest@sha256:ddf488ed2e281a0cecc5b4969fd84d3905f1e565e3c83aae8015f337a311415c
    pullPolicy: IfNotPresent
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.12.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  deployNodeAgent: true
  configuration:
    # defaultVolumesToFsBackup: true
    backupStorageLocation: null
    volumeSnapshotLocation: null
    namespace: cozy-velero
    features: EnableCSI
    # Increase timeout for item operations to 24 hours to prevent timeouts
    # during backups of very large volumes. The Velero default is 4 hours.
    defaultItemOperationTimeout: 24h
