kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.40.6@sha256:67713d00d0287eb883b8620c4d650dc2872561aec3ea7c618498c0205c763089
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v0.40.6@sha256:67713d00d0287eb883b8620c4d650dc2872561aec3ea7c618498c0205c763089
