kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.39.0@sha256:a8981fc592628855693aeeebc3a1f51058a8e667fa2405416b6ed1b1cbe86c09
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v0.39.0@sha256:a8981fc592628855693aeeebc3a1f51058a8e667fa2405416b6ed1b1cbe86c09
