kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.39.1@sha256:ab66ab206da1b8b2fe1aa623a4accd8c91d2c5560aa857f949ee9183d79087ad
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v0.39.1@sha256:ab66ab206da1b8b2fe1aa623a4accd8c91d2c5560aa857f949ee9183d79087ad
