kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.0.0-alpha.1@sha256:777f1df253dc97da7f42019857e7a893c34bd98da1cf36e38533adbdf601acf7
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.0.0-alpha.1@sha256:777f1df253dc97da7f42019857e7a893c34bd98da1cf36e38533adbdf601acf7
