kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.0.0-rc.2@sha256:69e00bbed5dedbd57f6c0e9d02d1c32b96d5ca1379d6b3af9338a3a8e5e9f6ab
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.0.0-rc.2@sha256:69e00bbed5dedbd57f6c0e9d02d1c32b96d5ca1379d6b3af9338a3a8e5e9f6ab
