kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.38.5@sha256:5e2e78c3b4b6c7cfe971a00c7798d20dbdff7d7b8bf277b136d0fcf74f94084f
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v0.38.5@sha256:5e2e78c3b4b6c7cfe971a00c7798d20dbdff7d7b8bf277b136d0fcf74f94084f
