kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.38.4@sha256:458b8ae75e845e08c3c3d20f8af0ea1d7f8933739609d19f266fbf280417b764
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v0.38.4@sha256:458b8ae75e845e08c3c3d20f8af0ea1d7f8933739609d19f266fbf280417b764
