cozystackOperator:
  image: ghcr.io/cozystack/cozystack/cozystack-operator:latest@sha256:f7f6e0fd9e896b7bfa642d0bfa4378bc14e646bc5c2e86e2e09a82770ef33181
  platformSourceUrl: 'oci://ghcr.io/cozystack/cozystack/cozystack-packages'
  platformSourceRef: 'digest=sha256:0576491291b33936cdf770a5c5b5692add97339c1505fc67a92df9d69dfbfdf6'
  cozystackVersion: latest
