# Digest for OCIRepository cozystack-packages
# This value is automatically updated by Makefile when building the image
packagesDigest: "sha256:a1c14def709ed07d4d0dc8a776143388115a36c30e3558d5c4974f55ef653f35"
