cozystackOperator:
  image: ghcr.io/cozystack/cozystack/cozystack-operator:latest@sha256:f20a7380e72e377b233b349a8513314fe72617bbf7cceb2a9731cb8ec9ea33d4
  disableTelemetry: false
  cozystackVersion: "latest"
  packagesDigest: sha256:73f930bdc12810604ccb116f1fb5df59ba3e03eab0b834c5b0e2f5e6327ab5e6
