cozystackOperator:
  image: ghcr.io/cozystack/cozystack/cozystack-operator:v1.0.0-beta.1@sha256:badec236da284eda2858337959086ae1efc90847b2980503cfaaba117600114e
  platformSourceUrl: 'oci://ghcr.io/cozystack/cozystack/cozystack-packages'
  platformSourceRef: 'digest=sha256:e9afb5bd00b301ebac90e408f02f86b3d155bbaf18717a3c7d1a6668129e97e0'
