cozystackOperator:
  image: ghcr.io/cozystack/cozystack/cozystack-operator:latest@sha256:5b25b3eb9bd85ba8843fe4f36af555cd0200d581f65ca711f9ccdd552e1aa258
  disableTelemetry: false
  cozystackVersion: "latest"
  packagesDigest: sha256:e89ff0473df1178e0c8a77dd6898892ca82d455c4d20e4afa5f649edf2d72218
