cozystack:
  image: ghcr.io/cozystack/cozystack/installer:v0.38.2@sha256:9ff92b655de6f9bea3cba4cd42dcffabd9aace6966dcfb1cc02dda2420ea4a15
cozystackOperator:
  image: ghcr.io/cozystack/cozystack/cozystack-operator:latest@sha256:446b4afe9ed160a850cc9b61dd6f34b2ae36d69d4cd974d6d35a25180bd73879
  packagesRepository: oci://ghcr.io/cozystack/cozystack/platform-packages
  packagesDigest: sha256:39666735999e79f3b7b502ff46c642e13a17ce8860a47493af0912285d360ec9
  cozystackVersion: latest
