cozystackOperator:
  image: ghcr.io/cozystack/cozystack/cozystack-operator:latest@sha256:1e998a7cf2b9ed10b1320d9b3282e9362283fcda524f22fa0ad40579e7e464ff
  platformSourceUrl: 'oci://ghcr.io/cozystack/cozystack/cozystack-packages'
  platformSourceRef: 'digest=sha256:319e78e454cdc28e1d6edd701e4b09723bfb12a03c71b77271d136b09002ad7e'
  cozystackVersion: latest
