{{- $systemBundleType := .Values.bundles.system.type | default "full" }}

{{- if or (ne $systemBundleType "full") (ne $systemBundleType "hosted") }}
{{    include "cozystack.render-glob" (list . "bundles/system/applicationdefinitions/*.yaml") }}
{{- end }}

{{- if .Values.bundles.iaas.enabled }}
{{    include "cozystack.render-glob" (list . "bundles/iaas/applicationdefinitions/*.yaml") }}
{{- end }}
{{- if .Values.bundles.paas.enabled }}
{{    include "cozystack.render-glob" (list . "bundles/paas/applicationdefinitions/*.yaml") }}
{{- end }}
{{- if .Values.bundles.naas.enabled }}
{{    include "cozystack.render-glob" (list . "bundles/naas/applicationdefinitions/*.yaml") }}
{{- end }}
