storageClasses:
  replicated:
    infraStorageClass: replicated
    default: true
csiDriver:
  image: ghcr.io/cozystack/cozystack/kubevirt-csi-driver:0.0.0@sha256:604561e23df1b8eb25c24cf73fd93c7aaa6d1e7c56affbbda5c6f0f83424e4b1
